/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

// import com.google.common.annotations.VisibleForTesting;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // TestCases tests = new TestCases(); // Initialize your test class

        // TODO: call your test case functions one after other here
        // Amazon searching=new Amazon();
        // searching.testcase() ;
        // searching.endTest();
        // Bookmyshow hyperlink=new Bookmyshow();
        // hyperlink. bookmyshow();
        // hyperlink.endTest();
        // Automate_post_on_linkedin autoPost=new Automate_post_on_linkedin();
        // autoPost. postimage();
        // autoPost.endTest();
        // Automate_image_urls autoImg=new Automate_image_urls();
        // autoImg.imgurl() ;
        // autoImg.endTest();
        // Automate_imdb_ratings imdb=new Automate_imdb_ratings();
        // imdb. imbdratng();
        // imdb.endTest();
        Automate_window_handle wh = new Automate_window_handle();
        wh.windowshandle();
        wh.endTest();
        // Frame fr=new Frame();
        // fr. frames();
        // fr.endTest();

        // tests.testCase01();

        // END Tests

        // tests.endTest(); // End your test by clearning connections and closing
        // browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();

    }
}
